Select * from sys.databases

CREATE DATABASE address_book;

use address_book

CREATE TABLE AddressBook
(
  FIRSTNAME VARCHAR(25),
  LASTNAME VARCHAR(25),
  ADDRESS VARCHAR(100),
  CITY VARCHAR(20),
  ZIP BIGINT,
  PHONENUMBER BIGINT,
  EMAIL VARCHAR(40)
)

alter table AddressBook add CONTACT BIGINT
alter table AddressBook add STATE VARCHAR(20)

SELECT * FROM AddressBook

INSERT INTO AddressBook VALUES
('SUMIT','PANDIT', '8/1/H', 'KOLKATA', '02', '8013229710','s@gmail.com', '7003756275','WB'),
('Sam','KUMAR', '4/1/8/H', 'KOLKATA', '98', '9013229710','sam@gmail.com', '8003756275','WB')

UPDATE AddressBook
SET CONTACT = '9099209933'
WHERE FIRSTNAME = 'SUMIT';

UPDATE AddressBook
SET STATE = 'WB'
WHERE FIRSTNAME = 'SUMIT' OR FIRSTNAME = 'AMIT' OR FIRSTNAME = 'Samul';

INSERT INTO AddressBook VALUES
('AMIT','GUPTA', '90/C', 'KOLKATA', '22', '679229710','amit@gmail.com', '5098756275','WB'),
('Samul','KUMAR', '108/2/k', 'KOLKATA', '38', '9013229710','sam@gmail.com', '6703756270','WB')

DELETE FROM AddressBook
WHERE FIRSTNAME = 'Sam';

INSERT INTO AddressBook VALUES
('RAHUL','GUPTA', '990/C', 'PUNE', '32', '8879229710','RAHUL@gmail.com', '9098756275','MAHA')

SELECT * FROM AddressBook where CITY='KOLKATA' OR STATE='WB'

SELECT COUNT(EMAIL) AS TOTALPERSON FROM AddressBook WHERE CITY='KOLKATA' 

SELECT * FROM AddressBook ORDER BY FIRSTNAME ASC

alter table AddressBook add TYPE VARCHAR(20)
alter table AddressBook add NAME VARCHAR(30)

UPDATE AddressBook
SET TYPE = 'BROTHER'
WHERE FIRSTNAME = 'SUMIT' OR FIRSTNAME = 'AMIT';
 
 UPDATE AddressBook
SET TYPE = 'COUSIN'
WHERE FIRSTNAME = 'RAHUL'

 UPDATE AddressBook
SET TYPE = 'SON'
WHERE FIRSTNAME = 'Samul'

UPDATE AddressBook
SET NAME = 'SUMIRAN'
WHERE FIRSTNAME = 'SUMIT';

UPDATE AddressBook
SET NAME = 'AMAN'
WHERE FIRSTNAME = 'AMIT';
 
 UPDATE AddressBook
SET NAME = 'RAVI'
WHERE FIRSTNAME = 'RAHUL'

 UPDATE AddressBook
SET NAME = 'SAMIR'
WHERE FIRSTNAME = 'Samul'



SELECT COUNT(TYPE) AS TOTALPERSON FROM AddressBook